### ISSUE TITLE
SSL Issue on Chrome Browser

### ISSUE THREAD

**Issue by habib-itopa** [CSC510-GROUP-40/FitnessApp#14]
**Describe the bug**
Cannot access the website on google chrome locally.

**To Reproduce**
1. Run the app in the terminal with this command 'export FLASK_APP=fitnessapp && export FLASK_ENV=development && FLASK_DEBUG=1 && flask run --cert=adhoc'
2. Go to google chrome address bar and type 'https://127.0.0.1:5000/login' to access the app'.

**Expected behavior**
See the error in the attached snapshot

**Screenshots**
<img width="1440" alt="image (1)" src="https://github.com/user-attachments/assets/3b3e69cf-f9cb-481c-be2a-69cf481c5fc1">

**Desktop**
 - OS: Windows and MAC Operating System.
 - Browser: chrome.

**Comment by kofiarkoh** [comment]
Fixed With #16

**Comment by kofiarkoh** [comment]
Fixed With #16
